FROM mr_consensus_base_eval3:latest

WORKDIR /builds

ENV MUPDF_VERSION=mupdf-1.16.1-source
RUN wget https://mupdf.com/downloads/archive/${MUPDF_VERSION}.tar.gz
RUN tar xvf ${MUPDF_VERSION}.tar.gz
RUN mv /builds/${MUPDF_VERSION} /builds/src
WORKDIR /builds/src
RUN make -j $(nproc) build=profile HAVE_X11=no HAVE_GLUT=no prefix=/usr/local install

WORKDIR /builds/src
COPY filters/mupdf.json /builds/src/
COPY filterfiles.py /builds/src/
RUN ["python3", "./filterfiles.py", "mupdf"]

WORKDIR /consensus

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers
COPY coverage.py /consensus/

ENV MR_PARSER=mupdf
