FROM mr_consensus_base_eval3:latest

WORKDIR /builds

ENV QPDF_VERSION=release-qpdf-10.1.0
RUN wget https://github.com/qpdf/qpdf/archive/refs/tags/${QPDF_VERSION}.tar.gz
RUN tar xvf ${QPDF_VERSION}.tar.gz
RUN mv /builds/qpdf-${QPDF_VERSION} /builds/src
WORKDIR /builds/src
RUN ./configure
RUN make -j $(nproc)
RUN make install

WORKDIR /builds/src
COPY filters/qpdf.json /builds/src/
COPY filterfiles.py /builds/src/
RUN ["python3", "./filterfiles.py", "qpdf"]

WORKDIR /consensus

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers
COPY coverage.py /consensus/

ENV LD_LIBRARY_PATH=/usr/local/lib

ENV MR_PARSER=qpdf
