FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
            git cmake build-essential libfreetype6-dev libfontconfig-dev \
            libjpeg-dev zlib1g-dev libopenjp2-7-dev qtbase5-dev \
            gobject-introspection libglib2.0-dev libgtk-3-dev \
            libgirepository1.0-dev libnss3-dev ca-certificates ssh wget \
            libpq-dev postgresql-client zlib1g-dev libgmp-dev pkg-config m4 valgrind \
            graphviz libncurses-dev zip software-properties-common python3-pip python3-dev \
            gawk jq vim

RUN pip3 install psycopg2
RUN pip3 install gprof2dot
RUN pip3 install pypng

ENV CFLAGS="-fprofile-arcs -ftest-coverage -pg -fno-omit-frame-pointer"
ENV CXXFLAGS="-fprofile-arcs -ftest-coverage -pg -fno-omit-frame-pointer"
ENV LDFLAGS="-lgcov --coverage -pg"

ENV PYTHONUNBUFFERED=1
ENTRYPOINT [ "python3", "/consensus/consensus.py" ]
