FROM mr_consensus_base_eval3:latest

RUN apt-get update && apt-get install -y ffmpeg

WORKDIR /consensus

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers
COPY coverage.py /consensus/

ENV MR_PARSER=ffmpeg
