FROM mr_consensus_base_eval3:latest

WORKDIR /builds

ENV MUPDF_VERSION=mupdf-1.16.1-source
RUN wget https://mupdf.com/downloads/archive/${MUPDF_VERSION}.tar.gz
RUN tar xvf ${MUPDF_VERSION}.tar.gz
RUN mv /builds/${MUPDF_VERSION} /builds/src
WORKDIR /builds/src
RUN make build=profile HAVE_X11=no HAVE_GLUT=no prefix=/usr/local install

WORKDIR /builds/src
COPY coverage-src-summary.sh /builds/src/
RUN /builds/src/coverage-src-summary.sh

WORKDIR /consensus

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers
COPY coverage.py /consensus/

CMD [ "/consensus/consensus.py" ]
