FROM mr_consensus_base_eval3:latest

RUN apt-get update && apt-get install -y --no-install-recommends default-jre

WORKDIR /consensus

RUN wget https://archive.apache.org/dist/pdfbox/2.0.17/pdfbox-app-2.0.17.jar

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers

ENV MR_PARSER=pdfbox
