FROM mr_consensus_base_eval3:latest

WORKDIR /builds

RUN pip3 install pdfminer.six==20201018

WORKDIR /consensus

WORKDIR /consensus
COPY consensus.py /consensus/
COPY parsers /consensus/parsers

ENV PYTHONUNBUFFERED=1
ENV MR_PARSER=pdfminer_six
ENTRYPOINT [ "/consensus/consensus.py" ]
