FROM postgres:12

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3-pip postgresql-plpython3-12

RUN python3 -m pip install --upgrade Pillow
RUN python3 -m pip install --upgrade numpy
