version: '3'
services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 9432:5432
    volumes:
      - /localdisk01/log_info/sri/ta1/data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    volumes:
      - ./db/conf:/flyway/conf
      - ./db/sql:/flyway/sql
    command: migrate
    depends_on:
      - postgres

volumes: 
  db-data:
