FROM python:3

RUN pip3 install polyfile
RUN pip3 install psycopg2

COPY file-features.py /file-features/
WORKDIR /file-features

ENV PYTHONUNBUFFERED=1
ENV MR_PARSER=polyfile
ENTRYPOINT ["python3", "./file-features.py"]
